name: "Mohmanyang"
description: "Food for thought. From my kitchen to yours, with love."
logo: "/img/logo.jpg"
github: [metadata]
markdown: kramdown
input: GFM
hard_wrap: false
gems:
   - jekyll-coffeescript
   - jekyll-paginate

paginate: 10
paginate_path: "page:num"
excerpt_separator: <!--excerpt-->