name: "Mohmanyang"
description: "Food for thought. From my kitchen to yours, with love."
url: "http://mohmanyang.com"
baseurl: "/base"
logo: "/img/logo.jpg"
github: [metadata]
markdown: kramdown
input: GFM
hard_wrap: false
gems:
   - jekyll-coffeescript
   - jekyll-paginate

paginate: 3
paginate_path: "page:num"